# השתמש בתמונה רשמית של Python
FROM python:3.9-slim

# עדכון pip
RUN pip install --upgrade pip

# התקנת תלויות
COPY requirements.txt /app/requirements.txt
WORKDIR /app
RUN pip install -r requirements.txt

# העתקת קוד ה-backend לתוך הקונטיינר
COPY . /app

# הפעלת השרת
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
